[profile.release]
panic = 'unwind'

[workspace]
members = [
    'node',
    'pallets/country',
    'pallets/block',
    'runtime',
]
exclude = [
    '/dapps/luckydraw',
    '/dapps/airdrop',
    '/dapps/countrytoken'
]
